# Generated by Django 3.2.9 on 2021-11-27 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0003_featuredads'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorites',
            field=models.ManyToManyField(related_name='featured_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FeaturedAds',
        ),
    ]
